### ISSUE TITLE
System.OutOfMemoryException during decompress

### ISSUE THREAD

**Issue by IlyaSemenov** [chromelyapps/cef-binaries-downloader#2]
Running a Chromely app always ends up like this on a 2GB Windows 7 machine:

```
2020-01-21 20:06:56.315 [INFO] CefLoader: Installing CEF runtime from http://opensource.spotify.com/cefbuilds
2020-01-21 20:06:56.648 [INFO] CefLoader: Load CEF for Windows X86, version 3865
2020-01-21 20:06:56.669 [INFO] CefLoader: Load index page http://opensource.spotify.com/cefbuilds/index.html#windows32_b
uilds
2020-01-21 20:06:59.118 [INFO] CefLoader: Found download URL http://opensource.spotify.com/cefbuilds/cef_binary_77.1.18%
2Bg8e8d602%2Bchromium-77.0.3865.120_windows32_minimal.tar.bz2
2020-01-21 20:06:59.277 [INFO] CefLoader: Parallel download cef_binary_77.1.18%2Bg8e8d602%2Bchromium-77.0.3865.120_windo
ws32_minimal.tar.bz2, 123MB
2020-01-21 20:06:59.418 [INFO] CefLoader: Load C:\Users\kengu\AppData\Local\Temp\tmp913D.tmp (97088808..129451745)
2020-01-21 20:06:59.423 [INFO] CefLoader: Load C:\Users\kengu\AppData\Local\Temp\tmp913E.tmp (64725872..97088807)
2020-01-21 20:06:59.451 [INFO] CefLoader: Load C:\Users\kengu\AppData\Local\Temp\tmp913F.tmp (32362936..64725871)
2020-01-21 20:06:59.454 [INFO] CefLoader: Load C:\Users\kengu\AppData\Local\Temp\tmp915F.tmp (0..32362935)
2020-01-21 20:07:38.854 [INFO] CefLoader: Download took 42195ms
2020-01-21 20:07:38.859 [INFO] CefLoader: Decompressing BZ2 archive
2020-01-21 20:08:01.474 [INFO] CefLoader: Decompress progress = 10%
2020-01-21 20:08:20.890 [INFO] CefLoader: Decompress progress = 20%
2020-01-21 20:08:40.840 [INFO] CefLoader: Decompress progress = 30%
2020-01-21 20:09:02.151 [INFO] CefLoader: Decompress progress = 40%
2020-01-21 20:09:07.985 [FATAL] CefLoader: Exception of type 'System.OutOfMemoryException' was thrown.
2020-01-21 20:09:08.015 [ERROR] Oops! Something went wrong.     Exception of type 'System.OutOfMemoryException' was thro
wn.        at System.IO.MemoryStream.set_Capacity(Int32 value)
   at System.IO.MemoryStream.EnsureCapacity(Int32 value)
   at System.IO.MemoryStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at ICSharpCode.SharpZipLib.Core.StreamUtils.Copy(Stream source, Stream destination, Byte[] buffer, Action`1 progress)

   at ICSharpCode.SharpZipLib.BZip2.BZip2.Decompress(Stream inStream, Stream outStream, Boolean isStreamOwner, Action`1
progressPercent)
   at Chromely.CefGlue.Loader.CefLoader.DecompressArchive()
   at Chromely.CefGlue.Loader.CefLoader.Load(ChromelyPlatform platform)
   at Chromely.CefGlue.BrowserWindow.CefBinariesLoader.Load(IChromelyConfiguration config)
info: Microsoft.Hosting.Lifetime[0]
      Application is shutting down...
```                                                                                                                       

The memory usage is about ~30 Mb until the BZ2 decompression phase, then it starts to grow very quickly and the app crashes with 40% success and ~600-700 Mb memory usage.

Any ideas or workarounds? Does it really need 1.5+ Gb memory to unpack properly?

**Comment by IlyaSemenov** [comment]
Oops, I think it's the wrong project. Will reopen in https://github.com/chromelyapps/Chromely/
